version: '3.8'

services:
  satis_frontal:
    image: nginx:alpine
    restart: always
    volumes:
# SANS FICHIER DE CONF:
#      - ./:/usr/share/nginx/html
# AVEC FICHIER DE CONF:    
#      - ./fichierdeconf.conf:/etc/nginx/conf.d/default.conf
#      - ./:/var/www/html
# AVEC CERTIFICAT TLS + FICHIER DE CONF :
      - ./fichierdeconfTLS.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/ssl/certs/ssl.crt
      - ./selfsigned.key:/etc/ssl/private/ssl.key
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
